version: "3.8"
services:
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - data/medusa/config:/config
      - data/medusa/tv:/tv
      - data/medusa/downloads:/downloads
      - data/medusa/scripts:/scripts
    ports:
      - 8081:8081
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ${HOME_DIR}/config:/config
      - ${HOME_DIR}/plex:/plex
    restart: unless-stopped
  rclone_putio_mount:
    container_name: torrents_uploader
    network_mode: host
    restart: unless-stopped
  torrents_unarchiver:
    container_name: torrents_unarchiver
    network_mode: host
    restart: unless-stopped
    depends_on:
      - rclone_putio_mount
  torrents_uploader:
    container_name: torrents_uploader
    network_mode: host
    restart: unless-stopped

volumes:
  data:
