version: "3.8"
services:
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ${HOME_DIR}/medusa/config:/config
      - ${HOME_DIR}/medusa/tv:/tv
      - ${HOME_DIR}/medusa/downloads:/downloads
      - ${HOME_DIR}/medusa/scripts:/scripts
    ports:
      - 8081:8081
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ${HOME_DIR}/config:/config
      - ${HOME_DIR}/plex:/plex
    restart: unless-stopped
